# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23589dc72e59c039a0373fe0c41c60433207268cba3615c0ef37f4da7714950d4504883f05264cd6a3a0054dd8ccde600d90fd71a751b10169758e419be33a12

test:
  secret_key_base: e9fd6bdeec7e8c51eb53046a323ec8102bf5173d196bdb97d0964cec75c2581a147bbb44dc4d03a8a5d0df9f90501a8cbce329a88289d797bd6e890252b55440

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
